services:
  db:
    image: postgres:17-alpine
    container_name: oued-eddahab-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: oued
      POSTGRES_PASSWORD: oued_dev
      POSTGRES_DB: oued_eddahab

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: